plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
branches: 
  - +([0-9])?(.{+([0-9]),x).x}
  - master
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
