# base.yml
.node-job:
  image: node:21.7.3-alpine
  before_script:
    - apk add --no-cache git openssh-client

.docker-job:
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_DRIVER: overlay2
    REGISTRY_URL: registry.inker.studio
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY_URL
    - export IMAGE_NAME=$REGISTRY_URL/inker-studio/inker-back
    - export BRANCH_TAG=$IMAGE_NAME:$CI_COMMIT_REF_SLUG
    - export SHA_TAG=$IMAGE_NAME:$CI_COMMIT_SHA

.release-job:
  extends: .node-job
  variables:
    GIT_AUTHOR_NAME: "GitLab CI"
    GIT_AUTHOR_EMAIL: "gitlab-ci@inker.studio"
    GIT_COMMITTER_NAME: "GitLab CI"
    GIT_COMMITTER_EMAIL: "gitlab-ci@inker.studio"