export enum ReminderType {
  // Pre-appointment reminders
  APPOINTMENT_24H_BEFORE = 'APPOINTMENT_24H_BEFORE',
  APPOINTMENT_2H_BEFORE = 'APPOINTMENT_2H_BEFORE', 
  APPOINTMENT_30MIN_BEFORE = 'APPOINTMENT_30MIN_BEFORE',
  
  // Post-appointment reminders
  REVIEW_REQUEST_24H_AFTER = 'REVIEW_REQUEST_24H_AFTER',
  REVIEW_REQUEST_48H_AFTER = 'REVIEW_REQUEST_48H_AFTER',
  PHOTO_REQUEST_IMMEDIATELY = 'PHOTO_REQUEST_IMMEDIATELY',
  
  // Consent reminders
  CONSENT_12H_BEFORE = 'CONSENT_12H_BEFORE',
  CONSENT_2H_BEFORE = 'CONSENT_2H_BEFORE',
  
  // Confirmation management
  CONFIRMATION_CHECK = 'CONFIRMATION_CHECK',
  CONFIRMATION_TIMEOUT_48H = 'CONFIRMATION_TIMEOUT_48H',
  
  // Reports
  MONTHLY_ARTIST_REPORT = 'MONTHLY_ARTIST_REPORT',
}

export enum CronJobType {
  PRE_APPOINTMENT_REMINDERS = 'PRE_APPOINTMENT_REMINDERS',
  POST_APPOINTMENT_FOLLOWUP = 'POST_APPOINTMENT_FOLLOWUP',
  PENDING_CONFIRMATION_CHECK = 'PENDING_CONFIRMATION_CHECK',
  CONSENT_REMINDERS = 'CONSENT_REMINDERS',
  MONTHLY_REPORTS = 'MONTHLY_REPORTS',
} 