export enum AppointmentAction {
  CONFIRM = 'CONFIRM',
  LEAVE_REVIEW = 'LEAVE_REVIEW',
  VIEW_DETAILS = 'VIEW_DETAILS',
  UPLOAD_PHOTOS = 'UPLOAD_PHOTOS',
  CONTACT_ARTIST = 'CONTACT_ARTIST',
  CONFIRM_CONSENT = 'CONFIRM_CONSENT',
}
