CREATE INDEX "IDX_50ece0401edd36c92ecfa43d5d" ON public.agenda_event CREATE INDEX "IDX_50ece0401edd36c92ecfa43d5d" ON agenda_event USING btree (start_date);
CREATE INDEX "IDX_5ad973140c6162b87c4780477c" ON public.agenda_event CREATE INDEX "IDX_5ad973140c6162b87c4780477c" ON agenda_event USING btree (end_date);
CREATE INDEX "IDX_0819be156d36ead6e3a10d7391" ON public.agenda_event CREATE INDEX "IDX_0819be156d36ead6e3a10d7391" ON agenda_event USING btree (quotation_id);
CREATE INDEX idx_agenda_id ON public.agenda_event CREATE INDEX idx_agenda_id ON agenda_event USING btree (agenda_id);
CREATE INDEX "IDX_703dc0714a96b3a6872d0978a1" ON public.agenda_event CREATE INDEX "IDX_703dc0714a96b3a6872d0978a1" ON agenda_event USING btree (start_date, end_date);
CREATE INDEX "IDX_085cd03c647cd3f2f2045dbbd0" ON public.agenda_unavailable_time CREATE INDEX "IDX_085cd03c647cd3f2f2045dbbd0" ON agenda_unavailable_time USING btree (start_date);
CREATE INDEX "IDX_76f0dc9ea1b280b659485e1c56" ON public.agenda_unavailable_time CREATE INDEX "IDX_76f0dc9ea1b280b659485e1c56" ON agenda_unavailable_time USING btree (end_date);
CREATE INDEX "IDX_9b0f71bc992eacc3909e1f3866" ON public.agenda_unavailable_time CREATE INDEX "IDX_9b0f71bc992eacc3909e1f3866" ON agenda_unavailable_time USING btree (start_date, end_date);
CREATE INDEX "IDX_c9083b6cdc404ea78948b7b625" ON public.agenda CREATE INDEX "IDX_c9083b6cdc404ea78948b7b625" ON agenda USING btree (artist_id);
CREATE INDEX "IDX_a9d713d3bd3c54be56263cb76e" ON public.quotation CREATE INDEX "IDX_a9d713d3bd3c54be56263cb76e" ON quotation USING btree (customer_id);
CREATE INDEX "IDX_95663d2c16f5445a1b677d5482" ON public.quotation CREATE INDEX "IDX_95663d2c16f5445a1b677d5482" ON quotation USING btree (artist_id);
CREATE INDEX idx_quotation_tattoo_design_cache_id ON public.quotation CREATE INDEX idx_quotation_tattoo_design_cache_id ON quotation USING btree (tattoo_design_cache_id);
CREATE INDEX idx_form_templates_artist_id ON public.form_templates CREATE INDEX idx_form_templates_artist_id ON form_templates USING btree (artist_id);
CREATE INDEX idx_form_templates_consent_type ON public.form_templates CREATE INDEX idx_form_templates_consent_type ON form_templates USING btree (consent_type);
CREATE INDEX idx_signed_consents_event_id ON public.signed_consents CREATE INDEX idx_signed_consents_event_id ON signed_consents USING btree (event_id);
CREATE INDEX idx_signed_consents_form_template_id ON public.signed_consents CREATE INDEX idx_signed_consents_form_template_id ON signed_consents USING btree (form_template_id);
CREATE INDEX idx_signed_consents_user_id ON public.signed_consents CREATE INDEX idx_signed_consents_user_id ON signed_consents USING btree (user_id);
CREATE INDEX idx_agenda_event_status ON public.agenda_event CREATE INDEX idx_agenda_event_status ON agenda_event USING btree (status);
CREATE INDEX "IDX_quotation_offers_quotation_id" ON public.quotation_offers CREATE INDEX "IDX_quotation_offers_quotation_id" ON quotation_offers USING btree (quotation_id);
CREATE INDEX "IDX_quotation_offers_artist_id" ON public.quotation_offers CREATE INDEX "IDX_quotation_offers_artist_id" ON quotation_offers USING btree (artist_id);
CREATE INDEX idx_agenda_event_deleted_at ON public.agenda_event CREATE INDEX idx_agenda_event_deleted_at ON agenda_event USING btree (deleted_at);
CREATE INDEX idx_penalty_user_id ON public.cancellation_penalty CREATE INDEX idx_penalty_user_id ON cancellation_penalty USING btree (user_id);
CREATE INDEX idx_penalty_event_id ON public.cancellation_penalty CREATE INDEX idx_penalty_event_id ON cancellation_penalty USING btree (event_id);
CREATE INDEX idx_penalty_agenda_id ON public.cancellation_penalty CREATE INDEX idx_penalty_agenda_id ON cancellation_penalty USING btree (agenda_id);
CREATE INDEX idx_penalty_quotation_id ON public.cancellation_penalty CREATE INDEX idx_penalty_quotation_id ON cancellation_penalty USING btree (quotation_id);
CREATE INDEX idx_penalty_status ON public.cancellation_penalty CREATE INDEX idx_penalty_status ON cancellation_penalty USING btree (status);
CREATE INDEX idx_penalty_type ON public.cancellation_penalty CREATE INDEX idx_penalty_type ON cancellation_penalty USING btree (type);
CREATE INDEX idx_agenda_event_reminder_sent ON public.agenda_event CREATE INDEX idx_agenda_event_reminder_sent ON agenda_event USING gin (reminder_sent);
CREATE INDEX idx_agenda_event_agenda_dates ON public.agenda_event CREATE INDEX idx_agenda_event_agenda_dates ON agenda_event USING btree (agenda_id, start_date, end_date);
CREATE INDEX idx_quotation_type_status ON public.quotation CREATE INDEX idx_quotation_type_status ON quotation USING btree (type, status);
CREATE INDEX idx_quotation_artist_status ON public.quotation CREATE INDEX idx_quotation_artist_status ON quotation USING btree (artist_id, status);
CREATE INDEX idx_quotation_appointment_date ON public.quotation CREATE INDEX idx_quotation_appointment_date ON quotation USING btree (appointment_date);
CREATE INDEX idx_quotation_offer_quotation_artist ON public.quotation_offers CREATE INDEX idx_quotation_offer_quotation_artist ON quotation_offers USING btree (quotation_id, artist_id);
CREATE INDEX idx_quotation_offer_estimated_date ON public.quotation_offers CREATE INDEX idx_quotation_offer_estimated_date ON quotation_offers USING btree (estimated_date);
CREATE UNIQUE INDEX "REL_a4be6d79f7ac6e0ff252361f5f" ON public.agenda_invitation CREATE UNIQUE INDEX "REL_a4be6d79f7ac6e0ff252361f5f" ON agenda_invitation USING btree (event_id);
CREATE INDEX "IDX_a4be6d79f7ac6e0ff252361f5f" ON public.agenda_invitation CREATE INDEX "IDX_a4be6d79f7ac6e0ff252361f5f" ON agenda_invitation USING btree (event_id);
CREATE INDEX "IDX_51cea2e92a1684c6f5dec0be77" ON public.agenda_event CREATE INDEX "IDX_51cea2e92a1684c6f5dec0be77" ON agenda_event USING btree (customer_id);
CREATE INDEX idx_quotation_offer_artist_date ON public.quotation_offers CREATE INDEX idx_quotation_offer_artist_date ON quotation_offers USING btree (artist_id, estimated_date);
