import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsNotEmpty, IsString } from 'class-validator';
import { DeviceType } from '../../database/entities/userFcmToken.entity';

export class RegisterFcmTokenRequestDto {
  @ApiProperty({
    description: 'FCM token generated by Firebase SDK',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  })
  @IsString()
  @IsNotEmpty()
  token: string;

  @ApiProperty({
    description: 'Device type',
    enum: DeviceType,
    example: DeviceType.WEB,
  })
  @IsEnum(DeviceType)
  @IsNotEmpty()
  deviceType: DeviceType;
}